BOOL __declspec(dllimport) SetLocalHook(LPCWSTR moduleName, LPCWSTR funcName, LPCWSTR callBackModuleName, LPCWSTR callBackFuncName);
BOOL __declspec(dllimport) SetGlobalHook(LPCWSTR moduleName, LPCWSTR funcName, LPCWSTR callBackModuleName, LPCWSTR callBackFuncName);
BOOL __declspec(dllimport) SetRemoteHook(LPCWSTR moduleName, LPCWSTR funcName, LPCWSTR callBackModuleName, LPCWSTR callBackFuncName, DWORD procId);
void __declspec(dllimport) RemoveLocalHook(LPCWSTR funcName);
void __declspec(dllimport) RemoveGlobalHook(LPCWSTR funcName);
void __declspec(dllimport) RemoveRemoteHook(LPCWSTR funcName, DWORD procId);
BOOL __declspec(dllimport) SetLocalHook(LPCWSTR moduleName, LPCWSTR funcName, UINT64 callBackAddress);
BOOL __declspec(dllimport) SetGlobalHook(LPCWSTR moduleName, LPCWSTR funcName, UINT64 callBackAddress);
BOOL __declspec(dllimport) SetRemoteHook(LPCWSTR moduleName, LPCWSTR funcName, DWORD procId, UINT64 callBackAddress);
BOOL __declspec(dllimport) SetLocalHook(UINT64 funcAddress, UINT64 callBackAddress);
BOOL __declspec(dllimport) SetGlobalHook(UINT64 funcAddress, UINT64 callBackAddress);
BOOL __declspec(dllimport) SetRemoteHook(UINT64 funcAddress, DWORD procId, UINT64 callBackAddress);
void __declspec(dllimport) RemoveLocalHook(UINT64 funcAddress);
void __declspec(dllimport) RemoveGlobalHook(UINT64 funcAddress);
void __declspec(dllimport) RemoveRemoteHook(UINT64 funcAddress, DWORD procId);
BOOL __declspec(dllimport) SetLocalHook(UINT64 funcAddress, LPCWSTR callBackModuleName, LPCWSTR callBackFuncName);
BOOL __declspec(dllimport) SetGlobalHook(UINT64 funcAddress, LPCWSTR callBackModuleName, LPCWSTR callBackFuncName);
BOOL __declspec(dllimport) SetRemoteHook(UINT64 funcAddress, LPCWSTR callBackModuleName, LPCWSTR callBackFuncName, DWORD procId);
BOOL __declspec(dllimport) UseStealth;